#!/bin/sh

# Please note this is tightly coupled with secrets and manifest gen.

msg="Please set an environment <jeff|prod|tiantan>";
environment=$1;
if [ -z $1 ]; then
    echo $msg;
    exit 1;
fi;

if [ $environment == "jeff" ]; then
    api="https://api.staging.cf-app.com";
else
    if [ $environment == "prod" ]; then
        api="https://api.run.pivotal.io";
    else
        if [ $environment == "tiantan" ]; then
            api="https://api.pivotalpws.cn";
        else
            echo "Unknown Environment Name"
            echo $msg;
            exit 1;
        fi;
    fi;
fi;

username='admin';
password=`ag  "properties_uaa_scim_users_0_password" $HOME/workspace/secrets-$environment/stubs/secrets-cf-aws-stub.json | head -n1 |cut -f 4 -d\"`

if [ -z $environment ]; then
    echo "Password not found, do you have the proper secrets directory in workspace?";
    exit 1;
fi;

cf api ${api};
cf auth ${username} ${password};
cf target -o "cloudops" -s "cloudops"
