#!/bin/sh

set -e # Exit if any command fails

all_the_repos

cd ~/workspace/pivotal-ide-prefs
cli/bin/ide_prefs install --ide=intellij
cli/bin/ide_prefs install --ide=webstorm
cli/bin/ide_prefs install --ide=gogland
