# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="agnoster-duet"

HYPHEN_INSENSITIVE="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(git chruby ruby aliases)

# User configuration

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

source $HOME/.zprofile
source $ZSH/oh-my-zsh.sh

# RPROMPT="hay"
# Stop zsh from autocompleting CD operations without typing cd
unsetopt AUTO_CD

alias be="bundle exec"

# This sets the characters that zsh understands as part of a word. Essentially,
# when you hit CTRL-w to delete a word, it will eat these characters too. Most
# importantly, the dash character. So with a path with dashes in it, you can
# use CTRL-w to remove the most recent directory, even if it has dashes! Bliss.
export WORDCHARS='*?_-.[]~=&;!#$%^(){}<>'

# Set Default Ruby
chruby 2.2.4

# Fuzzy completion for history
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

HOMEBREW_GITHUB_API_TOKEN="35e20d8c268682a33236eb50bdfacaac377719a0"

# Direnv hook
eval "$(direnv hook zsh)"
